name: SimpleCore
main: me.tsourtzis.simplecore.main.Main
version: 0.0.1
api-version: 1.16
author: tsourtzis

commands:
  heal:
    description: Restore a player's health.
    usage: /heal [player].
  kill:
    description: Take a player's life.
    usage: /kill [player].
  feed:
    description: Sate your hunger.
    usage: /feed [player].
  smite:
    description: Strike lightning upon a player.
    usage: /smite [player].
  ignite:
    description: Set a player on fire.
    usage: /ignite [player].
  teleport:
    description: Teleport to another player.
    usage: /teleport <player> [anotherPlayer].
    aliases: tp
  teleportblock:
    description: Block incoming teleports.
    usage: /teleportblock.
    aliases: [tpblock, tpb]
    
permissions:
  simplecore.*:
    description: Gives access to all SimpleCore commands.
    children:
      simplecore.heal.self: true
      simplecore.heal.other: true
      simplecore.kill.self: true
      simplecore.kill.other: true
      simplecore.feed.self: true
      simplecore.feed.other: true
      simplecore.smite.self: true
      simplecore.smite.other: true
      simplecore.ignite.self: true
      simplecore.ignite.other: true
      simplecore.teleport.self: true
      simplecore.teleportblock.self: true
  simplecore.heal.self:
    description: Allows you to heal yourself.
    default: op
  simplecore.heal.other:
    description: Allows you to heal other players.
    default: op
  simplecore.kill.self:
    description: Allows you to take your own life.
    default: op
  simplecore.kill.other:
    description: Allows you to take the life of other players.
    default: op
  simplecore.feed.self:
    description: Allows you to sate your own hunger.
    default: op
  simplecore.feed.other:
    description: Allows you to sate the hunger of other players.
    default: op
  simplecore.smite.self:
    description: Allows you to strike lighting upon yourself.
    default: op
  simplecore.smite.other:
    description: Allows you to strike lighting upon other players.
    default: op
  simplecore.ignite.self:
    description: Allows you to set yourself on fire.
    default: op
  simplecore.ignite.other:
    description: Allows you to set other players on fire.
    default: op
  simplecore.teleport.self:
    description: Allows you to teleport yourself to other players.
    default: op
  simplecore.teleportblock.self:
    description: Allows you to block incoming teleports.
    default: op