name: SimpleCore
main: me.tsourtzis.simplecore.main.Main
version: 0.0.1
api-version: 1.16
author: tsourtzis

commands:
  heal:
    description: Restore a player's health.
    usage: /heal [player].
  kill:
    description: Take a player's life.
    usage: /kill [player].
  feed:
    description: Sate your hunger.
    usage: /feed [player].
  teleport:
    description: Teleport to another player.
    usage: /teleport <player> [anotherPlayer].
    aliases: tp
  teleportblock:
    description: Block incoming teleports.
    usage: /teleportblock.
    
permissions:
  simplecore.*:
    description: Gives access to all SimpleCore commands.
    children:
      simplecore.heal.self: true
      simplecore.heal.other: true
      simplecore.kill.self: true
      simplecore.kill.other: true
      simplecore.feed.self: true
      simplecore.feed.other: true
  simplecore.heal.self:
    description: Allows you to heal yourself.
    default: op
  simplecore.heal.other:
    description: Allows you to heal other players.
    default: op
  simplecore.kill.self:
    description: Allows you to take your own life.
    default: op
  simplecore.kill.other:
    description: Allows you to take the life of other players.
    default: op
  simplecore.feed.self:
    description: Sate your own hunger.
    default: op
  simplecore.feed.other:
    description: Sate another player's hunger.
    default: op