name: SimpleCore
main: me.tsourtzis.simplecore.main.Main
version: 0.0.1
author: tsourtzis
api-version: 1.16

commands:
  heal:
    description: Restore a player's health.
    usage: /heal [player].